# repos:
#   - repo: https://github.com/oxsecurity/megalinter
#     rev: v5
#     hooks:
#       - id: mega-linter
#         name: MegaLinter
#         entry: mega-linter
#         language: system
#         types: [python]
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
